### PR TITLE
Remove specific deployment users

### PR DESCRIPTION
**Pull request by jeremypoulter**
AWS credentials need to be setup externally to executing the role

### CODE REVIEW

**Comment by JamesTimms** [comment]
Is this so the module relies on env variables? If so I'd prefer we have an explicit env lookup to make it more clear/readable.

**Comment by jeremypoulter** [comment]
Not specifically, just lets the AWS SDK sort it self out so should also work for a lot of other cases, lots of other similar PRs coming in

**Comment by JamesTimms** [comment]
@jeremypoulter does this even work with session tokens?

>  If parameters are not set within the module, the following environment variables can be used in decreasing order of precedence AWS_URL or EC2_URL, AWS_PROFILE or AWS_DEFAULT_PROFILE, AWS_ACCESS_KEY_ID or AWS_ACCESS_KEY or EC2_ACCESS_KEY, AWS_SECRET_ACCESS_KEY or AWS_SECRET_KEY or EC2_SECRET_KEY, AWS_SECURITY_TOKEN or EC2_SECURITY_TOKEN, AWS_REGION or EC2_REGION, AWS_CA_BUNDLE

**Review by JamesTimms — APPROVED** [review]
Approved based on our conversation on Teams. As long as this works for all current use cases then it's fine.

**Pull request merged**
